#!/bin/bash
#
# Runs after a commit.
CWHITE="\x1B[0m"
CGREEN="\x1B[32m"

echo -e "Commit successful!"
echo -e "  --- Please remember to ${CGREEN}push${CWHITE}. ---"
echo -e "************************************"
