#!/bin/bash
#
# Called by "git commit" with no arguments before doing a commit.
CWHITE="\x1B[0m"
CGREEN="\x1B[32m"
echo -e "************************************"

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --bool hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
	test $(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
	exit 1
fi

# Let's just bypass this for now:
#exit 0

# Remove trailing whitespace automatically.
# (TODO) sed -i 's/[ \t]*$//' "$1"

# If there are whitespace errors, print the offending file names and fail.
git diff-index --check --cached $against --
code=$?
if [ $code -ne 0 ]; then
  echo -e "- - - - -"
  echo -e "Please ${CGREEN}fix the issues${CWHITE} listed above, 'git add' those changes, and commit again."
  echo -e "  (In emergencies, bypass this check with --no-verify on the commit command.)"
  echo -e "********************************************************************************"
  exit $code
fi

exit 0
